// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc295.GrizzlynatorBase.commands;


import org.usfirst.frc295.GrizzlynatorBase.Robot;

import edu.wpi.first.wpilibj.command.CommandGroup;



/**
 *
 */
public class AutonomousMiddle extends CommandGroup //9 + 10
{

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public AutonomousMiddle(String gameData)
	{
		if(Robot.gameData.charAt(0) == 'L')
		{
			addSequential(new Waypoint(60,0,.8,false));
			addSequential(new Wait());
			addSequential(new Waypoint(0,-90,.5,false));
			addSequential(new Waypoint(36,0,.8,false));
			addSequential(new Wait());
			addSequential(new Waypoint(0,90,.5,false));
			addSequential(new Wait());
			//addSequential ultrasonic to switch
			addSequential(new Wait());
			//addSequential drop cube
			addSequential(new Waypoint(-6,0,.8,false));
			addSequential(new Wait());
			addSequential(new Waypoint(0,90,.5,false));
			addSequential(new Wait());
			//addSequential pick up cube
		}
		else if(Robot.gameData.charAt(0) == 'R')
		{
			addSequential(new Waypoint(60,0,.8,false));
			addSequential(new Wait());
			addSequential(new Waypoint(0,90,.5,false));
			addSequential(new Waypoint(36,0,.8,false));
			addSequential(new Wait());
			addSequential(new Waypoint(0,-90,.5,false));
			addSequential(new Wait());
			//addSequential ultrasonic to switch
			addSequential(new Wait());
			//addSequential drop cube
			addSequential(new Waypoint(-6,0,.8,false));
			addSequential(new Wait());
			addSequential(new Waypoint(0,-90,.5,false));
			addSequential(new Wait());
			//addSequential pick up cube
		}
		else
		{
			addSequential(new Waypoint(144,0,.8,false));// ;) 
		}
	}

	// Called just before this Command runs the first time
	@Override
	protected void initialize()
	{
	}


	// Called repeatedly when this Command is scheduled to run
	@Override
	protected void execute() //haha 69
	{
	}


	// Make this return true when this Command no longer needs to run execute()
	@Override
	protected boolean isFinished()
	{
		return false;
	}


	// Called once after isFinished returns true
	@Override
	protected void end()
	{
	}


	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	@Override
	protected void interrupted()
	{
	}
}
