// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc295.GrizzlynatorBase.commands;

import edu.wpi.first.wpilibj.command.Command;

/**
 * DEFAULT for SysShooterPaddle Subsystem If the switch signaling the retracted
 * status of the paddle, is not closed Run the motor (slowly) until it is.
 * Happens automatically by the DEFAULT command when no other command requires()
 * the SysShooterPaddle
 */
public class CmdShooterPaddleDefaultRetract extends Command
{

	public CmdShooterPaddleDefaultRetract()
	{
		// requires(Robot.sysShooterPaddle);
	}


	// Called just before this Command runs the first time
	@Override
	protected void initialize()
	{
	}


	// DEFAULT COMMAND FOR SysShooterPaddle
	// Called repeatedly when no other command requires() the SysShooterPaddle
	@Override
	protected void execute()
	{
		// Robot.sysShooterPaddle.retractPaddle();
	}


	// Make this return true when this Command no longer needs to run execute()
	@Override
	protected boolean isFinished()
	{
		return false;
	}


	// Called once after isFinished returns true
	@Override
	protected void end()
	{
		// Robot.sysShooterPaddle.stopPaddle();
	}


	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	@Override
	protected void interrupted()
	{
		end();
	}

}
