// RobotBuilder Version: 2.0

//

// This file was generated by RobotBuilder. It contains sections of

// code that are automatically generated and assigned by robotbuilder.

// These sections will be updated in the future when you export to

// Java from RobotBuilder. Do not put any code or make any change in

// the blocks indicating autogenerated code or it will be lost on an

// update. Deleting the comments indicating the section will prevent

// it from being updated in the future.



package org.usfirst.frc295.GrizzlynatorBase;



import org.usfirst.frc295.GrizzlynatorBase.commands.AutonomousLeft;


//import org.usfirst.frc295.GrizzlynatorBase.commands.CmdDriveTrainShifterSetHigh;

//import org.usfirst.frc295.GrizzlynatorBase.commands.CmdDriveTrainShifterSetLow;

import org.usfirst.frc295.GrizzlynatorBase.commands.*;



import edu.wpi.first.wpilibj.buttons.JoystickButton;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;



/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */

public class OI

{


	private JoystickDriver _joystickDriver = new JoystickDriver(0, JoystickDriver.JoystickType.XBOX);

	private JoystickOperator _joystickOperator = new JoystickOperator(1, JoystickOperator.JoystickType.XBOX);



	public OI()

	{
	
			JoystickButton _btnOpIntakeCube = _joystickOperator.getAutoIntake();
			_btnOpIntakeCube.whileHeld(new CmdIntakeCube());
			
			JoystickButton _btnOpManualIntakeCube = _joystickOperator.getManualIntakeCubeButton();
			_btnOpManualIntakeCube.whileHeld(new CmdManualIntakeCube());
			
			JoystickButton _btnOpManualDropCube = _joystickOperator.getManualDropCubeButton();
			_btnOpManualDropCube.whileHeld(new CmdManualDropCube());
					

	public JoystickDriver getJoystickDriver()

	{

		return _joystickDriver;

	}


	public JoystickOperator getJoystickOperator()

	{

		return _joystickOperator;

	}

}