// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc295.GrizzlynatorBase;

import org.usfirst.frc295.GrizzlynatorBase.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI 
{
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    private Joystick         _joystickDriver = new Joystick(0);
    private Joystick         _joystickOperator = new Joystick(1);

    public OI() 
    {
        //=====================================================================
        // SMART DASHBOARD COMMANDS 
        //=====================================================================

    	// SmartDashboard Button to start the Autonomous Command
        SmartDashboard.putData("Autonomous Command",  new AutonomousCommand());

        
        //=====================================================================
        // DRIVER JOYSTICK BUTTON COMMANDS 
        //=====================================================================
        JoystickButton _btnDriverA = new JoystickButton(_joystickDriver,1);
		_btnDriverA.whenPressed(new CmdDriveTrainSetSlow());
        SmartDashboard.putData("Cmd Drive Slow", new CmdDriveTrainSetSlow());
		
        JoystickButton _btnDriverY = new JoystickButton(_joystickDriver, 4);
        _btnDriverY.whenPressed(new CmdDriveTrainSetFast());	
        SmartDashboard.putData("Cmd Drive Fast", new CmdDriveTrainSetFast());
	
        JoystickButton _btnDriverB = new JoystickButton(_joystickDriver, 3);
		_btnDriverB.whenPressed(new CmdDriveTrainSetForwardArm());
        SmartDashboard.putData("Cmd Drive Forward Arm", new CmdDriveTrainSetForwardArm());	
		
        JoystickButton _btnDriverX = new JoystickButton(_joystickDriver, 2);
		_btnDriverX.whenPressed(new CmdDriveTrainSetForwardShooter());
        SmartDashboard.putData("Cmd Drive Forward Shooter", new CmdDriveTrainSetForwardShooter());

        
        //=====================================================================
        // OPERATOR JOYSTICK BUTTON COMMANDS 
        //=====================================================================
        //JoystickButton _btnOperator9 = new JoystickButton(_joystickOperator, 9);
		//_btnOperator9.whenPressed(new CmdShooterPaddleActivate());
        //SmartDashboard.putData("Cmd Shooter Paddle Activate", new CmdShooterPaddleActivate());
		
		
        //JoystickButton _btnOperator10 = new JoystickButton(_joystickOperator, 10);
		//_btnOperator10.whileHeld(new CmdShooterShootHigh());
        //SmartDashboard.putData("Cmd Shooter Spin Shoot", new CmdShooterShootHigh());
		
		
        //JoystickButton _btnOperator13 = new JoystickButton(_joystickOperator, 13);
		//_btnOperator13.whileHeld(new CmdShooterLoadHigh());
        //SmartDashboard.putData("Cmd Shooter Spin Load",   new CmdShooterLoadHigh());

    }

    public Joystick getJoystickDriver() 
    {
        return _joystickDriver;
    }

    public Joystick getJoystickOperator() 
    {
        return _joystickOperator;
    }
}

