// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc295.GrizzlynatorBase;


/**
 * The RobotMap is used to organize constants used in the program.
 * Provides easily recognizable names for the values
 * Constants will usually map the pins for sensors and actuators
 * This provides flexibility in changing the wiring, 
 * Significantly reduces the possibility of multiple allocation.
 */
public class RobotMap 
{
	// CAN IDs
    public static final   short  CAN_DRIVE_ESC_LEFT_FRONT             = 1;
    public static final   short  CAN_DRIVE_ESC_LEFT_BACK              = 2;
    public static final   short  CAN_DRIVE_ESC_RIGHT_FRONT            = 3;
    public static final   short  CAN_DRIVE_ESC_RIGHT_BACK             = 4;	

    // PWM PINS (0 - 20)
    public static final   short  PWM_DRIVE_ESC_LEFT_FRONT             = 0;
    public static final   short  PWM_DRIVE_ESC_LEFT_BACK              = 1;
    public static final   short  PWM_DRIVE_ESC_RIGHT_FRONT            = 2;
    public static final   short  PWM_DRIVE_ESC_RIGHT_BACK             = 3;
    
    public static final   short  PWM_SHOOTER_PADDLE_ESC               = 6;
    public static final   short  PWM_SHOOTER_AIMER_ESC                = 15; //22
    public static final   short  PWM_SHOOTER_ESC_LEFT                 = 17;
    public static final   short  PWM_SHOOTER_ESC_RIGHT                = 20; //17

    // DIGITAL IO PINS
    public static final   short  DIO_DRIVE_ENC_RIGHT_CHAN1            = 0;
    public static final   short  DIO_DRIVE_ENC_RIGHT_CHAN2            = 1;
    public static final   short  DIO_DRIVE_ENC_LEFT_CHAN1             = 2;
    public static final   short  DIO_DRIVE_ENC_LEFT_CHAN2             = 3;
 
    public static final   short  DIO_SHOOTER_PADDLE_RETRACTED_SWITCH  = 4;

    
    // RELAY PINS
    public static final   short  RLY_GREENLIGHT                       = 0;
    public static final   short  RLY_FLASHLIGHT                       = 1;

    
    public static void init()
    {
    }
}
