// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc295.GrizzlynatorBase;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap 
{
	
    public static final   short  CAN_DRIVE_ESC_LEFT_FRONT             = 11;
    public static final   short  CAN_DRIVE_ESC_LEFT_BACK              = 22;
    public static final   short  CAN_DRIVE_ESC_RIGHT_FRONT            = 15;
    public static final   short  CAN_DRIVE_ESC_RIGHT_BACK             = 10;	

    
    public static final   short  PWM_DRIVE_ESC_LEFT_FRONT             = 1;
    public static final   short  PWM_DRIVE_ESC_LEFT_BACK              = 2;
    public static final   short  PWM_DRIVE_ESC_RIGHT_FRONT            = 3;
    public static final   short  PWM_DRIVE_ESC_RIGHT_BACK             = 4;
    
    public static final   short  PWM_SHOOTER_PADDLE_ESC               = 6;
    public static final   short  PWM_SHOOTER_AIMER_ESC                = 15; //22
    public static final   short  PWM_SHOOTER_ESC_LEFT                 = 17;
    public static final   short  PWM_SHOOTER_ESC_RIGHT                = 22; //17

    
    public static final   short  DIO_SHOOTER_PADDLE_RETRACTED_SWITCH  = 1;

    public static final   short  DIO_DRIVE_ENC_RIGHT_CHAN1            = 15;
    public static final   short  DIO_DRIVE_ENC_RIGHT_CHAN2            = 16;
    public static final   short  DIO_DRIVE_ENC_LEFT_CHAN1             = 17;
    public static final   short  DIO_DRIVE_ENC_LEFT_CHAN2             = 18;

    

    public static final   short  RLY_FLASHLIGHT                       = 7;

    public static void init()
    {
    }
}
